### ISSUE TITLE
Align naming

### ISSUE THREAD

**Issue by 1977er** [freifunkh/nodesjson-cli#3]
...

**Comment by AiyionPrime** [comment]
Align the naming of what?

**Comment by 1977er** [comment]
This looks totally like one of the other little helper tools from https://github.com/freifunkh/ansible/tree/master/roles/ffh.cli_tools/files/bin

I would move the development to that place and rename the tool to something like `ffh_resolve_node.sh`.

**Comment by lemoer** [comment]
If you want to rewrite the python script in shell, go ahead ;-)

**Comment by 1977er** [comment]
`s/\.sh$//`

**Comment by AiyionPrime** [comment]
It was last removed  in freifunkh/ansible@0733257ee45109b38ecd2730ead1c4717b96c250 iirc.

**Comment by AiyionPrime** [comment]
Is this even being deployed on supernodes via ansible?
I always thought it was an unrelated tool meant for your PC to work with our json files.

**Comment by 1977er** [comment]
My sole intention was to keep the Github freifunkh namespace comprehensible.
